version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: delist_user
      POSTGRES_PASSWORD: delist_password
      POSTGRES_DB: delist_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U delist_user -d delist_db"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
